name: Continuous Integration

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Install dependencies
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
          go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger docs
        run: make swag

      - name: Lint
        run: make lint

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -v ./...

