name: Continuous Integration

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Install dependencies
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
          go install github.com/swaggo/swag/cmd/swag@latest
          go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest

      - name: Generate Swagger docs
        run: make swag

      - name: Lint
        run: make lint

      - name: Build
        run: go build ./...

      - name: Run tests
        run: |
          set -euo pipefail
          go test -json -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
